Feature/ikas-missing-api-doc
Navlungo/express-api-docs pull request #1
Opened 2021-12-30 12:14 UTC by zikriyeurkmezcengiz

* Ikas api dokumantasyonu tamamlandı.

2021-12-30 12:16 UTC, zikriyeurkmezcengiz commented
@ilhancengiz @mutluboz  dokümantasyonu review eder misiniz? Tşk.

2021-12-30 13:41 UTC, ilhancengiz requested changes
eline sağlık @zikriyeurkmezcengiz çok güzel olmuş bence 🤩  gözüme çarpan typo'ları yada copy paste kalan yerleri belirttim. Birkaç api için de ek yorumum oldu✌🏼

2021-12-30 13:41 UTC, ilhancengiz commented on search/README.md
> +| **originRegion** <br>_opsiyonel_     | Yükün çıkışının yapılcağı bölgenin kodu. Tercihen posta kodu gönderilmeli. Bu alanın doğru gönderilmemesi durumunda fiyatlara ek iç taşıma maliyetleri yansıtı
yapılcağı

2021-12-30 13:41 UTC, ilhancengiz commented on search/README.md
> +| **type** <br>_zorunlu_     | Paket türü. Box veya Envelope olmalı. (büyük küçük harf duyarlı)             | string  |
type'ı count'un üstüne alsak daha iyi olabilir

2021-12-30 13:41 UTC, ilhancengiz commented on search/README.md
> +| **weight** <br>_zorunlu_   | Paketin ağırlığı. Envelope tipindeki paketler için en fazla 2.5 kg olabilir. | decimal |
kg cinsinden olma zorunluluğu varsa belirtmek iyi olur.

2021-12-30 13:41 UTC, ilhancengiz commented on search/README.md
> +| **width** <br>_opsiyonel_  | Paketin eni. Box tipindeki paketlerde bu değer zorunludur.                   | decimal |
cm cinsinden vs gibi standart ölçüm birimini belirtsek iyi olur sanki.

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +Navlungo kullanıcıları mağazalarını bağlarak siparişlerini Navlungo arayüzlerinde görüntüleyebilmektedir. Bu Api'ler ile sisteme kayıt olmuş bir kullanıcı arayüze girmeden mağazasını bağlayabilir ve
bağlarak -> bağlayarak

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +| **name** <br>_zorunlu_           | Yükün çıkışının yapılacağı ülkenin ISO2 kodu                                                                                                                  | st
Mağaza adı gibi bir şey olmalı sanki burası copy paste kalmış ?

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +| **thirdLine** <br>_zorunlu_            | Üçüncü adres satırı                                                                           | string |
bu fazla kalmış gibi

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +| **storeAddress** <br>_opsiyonel_ | Çözüm ortağı           | <[Address](#address)> object |
açıklama güncellenmeli

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +| **Body**  | **address** <br>_zorunlu_ | Mağaza adı            | <[Address](#address)> object |
açıklama güncellenmeli.

2021-12-30 13:41 UTC, ilhancengiz commented on store/README.md
> +| **Body**  | **address** <br>_zorunlu_ | Mağaza adı            | <[Address](#address)> object |
açıklama güncellenmeli

2021-12-30 13:41 UTC, ilhancengiz commented on store/order/README.md
> +| **creationDateInStore** <br>_opsiyonel_ | Siparişin mağazasında ilk yaratıldığı tarih | long                                   |
unix epoch timestamp (saniye cinsinden)

2021-12-30 13:41 UTC, ilhancengiz commented on store/order/README.md
> +### OrderLine
Bunu değiştirme şansımız varsa bence OrderItem daha güzel olur.

2021-12-30 13:41 UTC, ilhancengiz commented on store/order/README.md
> +| **orderLines** <br>_zorunlu_            | Kontak kişinin telefon numarası             | <[OrderLine](#orderLine)> array        |
açıklama güncellenmeli + en az 1 line(item) olmalı.

2021-12-30 13:41 UTC, ilhancengiz commented on store/order/README.md
> +| **price** <br>_zorunlu_       | Ürünün satış bedeli                                                  | string  |
currency sabit mi burada ? sabitse belirtmemiz lazım sanki.

2021-12-30 13:41 UTC, ilhancengiz commented on store/order/README.md
> +| **harmonyCode** <br>_zorunlu_ | Ürünün sınıflandırılmasında kullanılan muhteviyat kodu               | strig   |
gtipler karşı tarafta olacak mı ? bunun da listing api gibi bişeyi açılması gerekebilir sanki eğer zorunlu ise.

2022-01-03 06:50 UTC, zikriyeurkmezcengiz commented on store/order/README.md
> +| **harmonyCode** <br>_zorunlu_ | Ürünün sınıflandırılmasında kullanılan muhteviyat kodu               | strig   |
Global code ları kullanmalarını bekliyoruz.

2022-01-03 06:51 UTC, zikriyeurkmezcengiz commented
@ilhancengiz  fixledim. Tekrar bakar mısın?

2022-01-03 11:31 UTC, ilhancengiz requested changes
gözüme takılan bir açıklama oldu sadece onun dışında ok bence, eline sağlık @zikriyeurkmezcengiz✌🏼

2022-01-03 11:31 UTC, ilhancengiz commented on store/README.md
> +| **storeAddress** <br>_opsiyonel_ | Çözüm ortağı           | <[Address](#address)> object |
açıklama güncellenmeli sanki

2022-01-04 07:35 UTC, zikriyeurkmezcengiz commented
@ilhancengiz  one more time :)

2022-01-04 16:50 UTC, mutluboz approved these changes

2022-01-04 16:50 UTC, mutluboz commented
perfecto. @ilhancengiz  @zikriyeurkmezcengiz  ellerinize sağlık

2022-01-04 16:50 UTC, merged